language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
    - sudo apt-get update > /dev/null

install:
    - sudo apt-get install -y --force-yes php5-sqlite

script:
    - composer self-update
    - composer install -n --prefer-source
    - ./bin/phpspec run -f pretty
    - ./bin/behat --no-snippets --no-paths --verbose --format=progress